# Generated by Django 5.0.7 on 2024-08-06 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Patient',
        ),
    ]
